spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tx_user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#关闭thymeleaf模板引擎的缓存
  thymeleaf:
    cache: false
#我们的配置文件的真实位置
  messages:
    basename: i18n.login
#时间格式化标准
  mvc:
    format:
      date: yyyy-MM-dd